CREATE DATABASE IF NOT EXISTS pharmacie;
USE pharmacie;


CREATE TABLE IF NOT EXISTS Medicament (
    id_m INT AUTO_INCREMENT PRIMARY KEY,
    libelle varchar(50),
    quantite INT,
    prix FLOAT
);

CREATE TABLE IF NOT EXISTS Fournisseur (
    id_f INT AUTO_INCREMENT PRIMARY KEY,
    nom_fournissuer varchar(50)
);

CREATE TABLE IF NOT EXISTS Client (
    id_c INT AUTO_INCREMENT PRIMARY KEY,
    nom_client varchar(50)
);


CREATE TABLE IF NOT EXISTS Shipment(
    id_sh INTEGER AUTO_INCREMENT PRIMARY KEY,
    id_f INTEGER ,
    requeste_date DATETIME NOT NULL,
    received BOOLEAN NOT NULL,
    receipt
    _date DATETIME NOT NULL,
    CONSTRAINT for_for FOREIGN KEY(id_f) REFERENCES Fournisseur(id_f) ON DELETE CASCADE ON UPDATE CASCADE
    
);

CREATE TABLE IF NOT EXISTS ShipmentGood(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    id_sh INTEGER,
    id_m INTEGER ,
    quantite INTEGER NOT NULL,    
    CONSTRAINT for_med FOREIGN KEY(id_m) REFERENCES Medicament(id_m) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT for_sh FOREIGN KEY(id_sh) REFERENCES Shipment(id_sh) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS SaleProduct(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    id_m INTEGER ,
    id_s INTEGER,
    quantite INTEGER NOT NULL,
    
    CONSTRAINT for_med FOREIGN KEY(id_m) REFERENCES Medicament(id_m) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT for_sal FOREIGN KEY(id_s) REFERENCES Sale(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Sale(
    id INTEGER PRIMARY KEY,
    id_c INTEGER,
    dateV DATETIME NOT NULL,
    CONSTRAINT for_cli FOREIGN KEY(id_c) REFERENCES Client(id_c) ON DELETE CASCADE ON UPDATE CASCADE    

);